import color from 'mauw/colors';

/**
 * Computes a simple similarity score between two strings.
 *
 * This is a lightweight heuristic intended for CLI suggestions,
 * where performance and "good enough" results are preferred
 * over complex string distance algorithms.
 *
 * The comparison is:
 * - Case-insensitive
 * - Position-based (matching characters at the same index)
 *
 * The resulting score is a ratio between 0 and 1, where:
 * - 1 means identical strings
 * - 0 means no positional similarity
 *
 * @param _a - First string to compare.
 * @param _b - Second string to compare.
 * @returns A similarity score between 0 and 1.
 */
const similarity = (_a: string, _b: string): number => {
	const a = _a.toLowerCase();
	const b = _b.toLowerCase();

	let matches = 0;
	const len = Math.min(a.length, b.length);

	for (let i = 0; i < len; i++) {
		if (a[i] === b[i]) matches++;
	}

	return matches / Math.max(a.length, b.length);
};

/**
 * Resolves a human-friendly hint message based on expected values
 * and the value actually received.
 *
 * Behavior:
 * - If `hint` is falsy, no hint is returned.
 * - If `hint` is a string, it is treated as an explicit hint and
 *   returned as-is.
 * - If `hint` is `true`, an automatic hint is generated by comparing
 *   the received value against the expected values using a simple
 *   similarity heuristic.
 *
 * Automatic hints are only returned if:
 * - There is at least one expected and one received value.
 * - The best similarity score meets a minimum threshold, to avoid
 *   irrelevant or misleading suggestions.
 *
 * @param hint - Controls hint behavior (disabled, explicit, or automatic).
 * @param expected - List of expected values to compare against.
 * @param received - List of received values (only the first one is used).
 * @returns A formatted hint string, or null if no suitable hint exists.
 */
export function resolveHint(
	hint: boolean | string | undefined,
	expected: unknown[],
	received: unknown[],
): string | null {
	// Hint disabled
	if (!hint) return null;

	// Explicit hint provided by the caller
	if (typeof hint === 'string') {
		return hint;
	}

	// Automatic hint requires comparable values
	if (!expected.length || !received.length) return null;

	const receivedValue = String(received[0]);

	let bestMatch: { value: string; score: number } | null = null;

	for (const exp of expected) {
		const value = String(exp);
		const score = similarity(value, receivedValue);

		if (!bestMatch || score > bestMatch.score) {
			bestMatch = { value, score };
		}
	}

	// Minimum threshold to avoid meaningless suggestions
	if (bestMatch && bestMatch.score >= 0.4) {
		return `Did you mean ${color.green(`"${bestMatch.value}"`)}?`;
	}

	return null;
}
